version: "3"
services:
  admin:
    image: augustash/alpine-magento-cli:1.0.2
    networks:
      - private-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 64000
    depends_on:
      - mysql
    volumes:
      - data-src:/src
      - ./conf/auth.json:/.composer/auth.json
    env_file: env/magento.env
    environment:
      - MAGENTO_VERSION=2.2.1
      - MAGENTO_INSTALL_DB=true
      - MAGENTO_USE_SAMPLE_DATA=true
